server:
  port: 8081

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/todolist?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: skillbox
    driver-class-name : com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    genertate-dll: true
    hibernate:
      dll-auto: update
db:
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    hbm2dll:
      auto: update


